# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68f26a6c50a4d07bfcdd578d9c97064c8d33a3cb17d5d18b8c55afbace89e22736030a0d10bfbcd176c87bf8b3ae7a3d95b34ed5a7ac2b0c6bf252cf9a6ec09

test:
  secret_key_base: 9a5f17f0b1b85476f237d44d8c719b19bfda3ac9ee22e132342bbf1246526f36397fe2d2e9a2f6c0baac98e2706db7fce6a3109437ecbfa023a8d0de21f0a974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
